[package]
name = "birb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
list-any = "0.2.1"
parking_lot = "0.12.1"
rayon = "1.8.0"

[dev-dependencies]
rayon = "1.8.0"
