[package]
name = "birb_registry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
birb = { version = "0.1.0", path = "../birb" }
serde = "1.0.193"
serde_json = "1.0.108"
